[build]
  publish = "."
  command = "npm run build"

# 🔒 Desactiva el escaneo automático de secretos
[build.environment]
  NETLIFY_SECRETS_SCAN_ENABLED = "false"
  NETLIFY_DISABLE_SECRET_SCAN = "true"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "true"
