backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

site_url: "https://www.lunatravel25.com"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - label: "Inicio"
        name: "inicio"
        file: "data/inicio.json"
        fields:
          - { label: "Título principal", name: "main_title", widget: "string" }
          - { label: "Descripción", name: "description", widget: "text" }

      - label: "Servicios"
        name: "servicios"
        file: "data/servicios.json"
        fields:
          - { label: "Título de sección", name: "section_title", widget: "string" }
          - label: "Lista de servicios"
            name: "items"
            widget: "list"
            fields:
              - { label: "Nombre", name: "title", widget: "string" }
              - { label: "Descripción", name: "description", widget: "text" }
              - { label: "Imagen", name: "image", widget: "image", required: false }

  - name: "gallery"
    label: "Galería"
    folder: "data/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "testimonials"
    label: "Testimonios"
    folder: "data/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Comentario", name: "message", widget: "text" }
      - { label: "Foto (opcional)", name: "photo", widget: "image", required: false }
