backend:
  name: github
  repo: sotoalexs901/LunaTravel-Website
  branch: main
  base_url: https://api.netlify.com
  auth_type: pkce

publish_mode: editorial_workflow

media_folder: "uploads"
public_folder: "/uploads"

site_url: https://www.lunatravel25.com

collections:
  - name: "pricing"
    label: "Precios y Servicios"
    file: "data/pricing.json"
    fields:
      - { label: "Servicios", name: "servicios", widget: "list", fields:
          [
            { label: "Nombre (ES)", name: "name_es", widget: "string" },
            { label: "Precio", name: "price", widget: "string" },
            { label: "Descripción (ES)", name: "desc_es", widget: "text" }
          ] }

  - name: "contact"
    label: "Contacto"
    file: "data/contact.json"
    fields:
      - { label: "Correo electrónico", name: "email", widget: "string" }
      - { label: "Teléfono", name: "phone", widget: "string" }
      - { label: "WhatsApp", name: "whatsapp", widget: "string" }
      - { label: "Dirección", name: "address", widget: "string" }

  - name: "gallery"
    label: "Galería de Fotos"
    folder: "uploads/gallery"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "testimonials"
    label: "Testimonios"
    file: "data/testimonials.json"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Comentario", name: "comment", widget: "text" }



