backend:
  name: auth0
  label: "Auth0"
  domain: dev-fu7ju2qp5x2aibyo.us.auth0.com
  client_id: uThgjHy6pU27FPpyOLMkSLjFv2TGGso8
  redirect_uri: https://www.lunatravel25.com/admin/callback

media_folder: "uploads"
public_folder: "/uploads"

site_url: https://www.lunatravel25.com

collections:
  - name: "pricing"
    label: "Precios y Servicios"
    file: "data/pricing.json"
    fields:
      - { label: "Nombre (ES)", name: "name_es", widget: "string" }
      - { label: "Nombre (EN)", name: "name_en", widget: "string" }
      - { label: "Precio", name: "price", widget: "string" }
      - { label: "Descripción (ES)", name: "desc_es", widget: "text" }
      - { label: "Descripción (EN)", name: "desc_en", widget: "text" }

  - name: "contact"
    label: "Contacto"
    file: "data/contact.json"
    fields:
      - { label: "Correo electrónico", name: "email", widget: "string" }
      - { label: "Teléfono", name: "phone", widget: "string" }
      - { label: "WhatsApp", name: "whatsapp", widget: "string" }
      - { label: "Dirección", name: "address", widget: "string" }

  - name: "gallery"
    label: "Galería de Fotos"
    folder: "uploads/gallery"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "testimonials"
    label: "Testimonios"
    folder: "data/testimonials"
    create: true
    extension: "json"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Comentario", name: "comment", widget: "text" }
