<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Luna Travel CMS</title>

    <!-- Cargar Netlify CMS -->
    <script src="https://unpkg.com/netlify-cms-app@^2.15.72/dist/netlify-cms.js"></script>
  </head>

  <body>
    <h2 style="text-align:center; margin-top:20%;">Cargando panel de administración...</h2>

    <script>
      // Inicializa el CMS correctamente con la sintaxis actual
      window.CMS_MANUAL_INIT = true;

      window.addEventListener("load", function () {
        if (typeof CMS !== "undefined") {
          CMS.init({ configPath: "/admin/config.yml" });
        } else {
          console.error("CMS no se ha cargado correctamente.");
        }
      });
    </script>
  </body>
</html>
